// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArF_YdvSWqbSR8-PIfvd2ytxY1tKVzsZw',
    appId: '1:22629038852:android:fc0f7acedf9b618b0fae51',
    messagingSenderId: '22629038852',
    projectId: 'pottery-tracker-31b1f',
    storageBucket: 'pottery-tracker-31b1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-gT63i1UsP-c-fAUqNqRijLOpOIlGuzU',
    appId: '1:22629038852:ios:21037012b59e03d00fae51',
    messagingSenderId: '22629038852',
    projectId: 'pottery-tracker-31b1f',
    storageBucket: 'pottery-tracker-31b1f.firebasestorage.app',
    iosClientId:
        '22629038852-m2kc56p1cpo0hdq6oriq1e8r60do77dj.apps.googleusercontent.com',
    iosBundleId: 'com.albertxu.potterytracker',
  );
}
